---
title: "DataCleaning"
author: "Anh Vo"
date: "2022-11-17"
output: html_document
---

```{r}
data <- read_excel("/Users/anh.vo/Downloads/tabn104.10_edu_completion.xls", skip = 4)
data <- data[, c(1,2,4,7,10,12,14,16,18,20)]
names(data) <- c("Year","Total", "White", "Black", "Hispanic", "Total_Asian_Pacific", "Asian", "Pacific_Islander", "USIndian_AlaskaNative", "Two_more_races")
```

```{r}
total_hscomplete <- data[c(30:48), ]
total_baccomplete <- data[c(77:95), ]
male_hscomplete <- data[c(112:130), ]
male_baccomplete <- data[c(146:164), ]
female_hscomplete <- data[c(181:199), ]
female_baccomplete <- data[c(215:233), ]
```

```{r}
male_hscomplete$Gender <- rep("Male", len = nrow(male_hscomplete))
male_hscomplete$Education_Level <- rep("High School or higher", len = nrow(male_hscomplete))
female_hscomplete$Gender <- rep("Female", len = nrow(female_hscomplete))
female_hscomplete$Education_Level <- rep("High School or higher", len = nrow(female_hscomplete))

male_baccomplete$Gender <- rep("Male", len = nrow(male_baccomplete))
male_baccomplete$Education_Level <- rep("Bachelor's or higher degree", len = nrow(male_baccomplete))
female_baccomplete$Gender <- rep("Female", len = nrow(female_baccomplete))
female_baccomplete$Education_Level <- rep("Bachelor's or higher degree", len = nrow(female_baccomplete))
```

```{r}
male <- rbind(male_hscomplete, male_baccomplete)
female <- rbind(female_hscomplete, female_baccomplete)
```

```{r}
alledu <- rbind(male, female)
```



#################################################################################

```{r}
enrollment <- read_excel("/Users/anh.vo/Downloads/tabn105.30_enrollment_institution.xls", skip = 4)
enrollment <- enrollment[c(26:44), -c(8,10,12)]
names(enrollment) <- c("Year","Total_Enrollment", "Total_Elem_Sec", "Total_public", "Public_Prekindergarden_grade8", "Public_Grade9_Grade12", "Total_private", "Private_Prekindergarden_grade8", "Private_Grade9_Grade12", "Total_postsec", "Public_postsec", "Private_postsec")
```



```{r}
enrollment <- enrollment %>%
  mutate(Year = substr(Year, 6, 9))
```



#################################################################################


```{r}
expenditures <- read_excel("/Users/anh.vo/Downloads/tabn106.10_expenditures.xls", skip = 4)
expenditures <- expenditures[c(43:59), c(1,2, 5:7, 9,10,12, 3)]
names(expenditures) <- c("Year","GDP", "All_edu_exp", "All_GDP_perc", "All_elem_exp", "All_elem_GPD", "All_postsec_exp", "All_postsec_GPD", "School year")
```

##################################################################################


```{r}
gdp_income <- read_excel("/Users/anh.vo/Downloads/tabn106.60_gpdincome.xls", skip = 3)
gdp_income <- gdp_income[c(39:55), ]
names(gdp_income) <- c("Year","GDP_billions", "chained_GDP_billions", "All_expenditures", "Edu_expenditures", "National_income_billions", "Personal_income_billions", "chained_Disposable_income_billions", "Disposable_income_percap", "chained_Disposable_income_percap", "Median_family_income", "constant_Median_family_income", "midyear_pop_thousands", "July_pop_thousands")
```


###################################################################################

```{r}
earnings <- read_excel("/Users/anh.vo/Downloads/tabn502.20_earnings.xls", skip = 7)
earnings <- earnings[, c(1,2,4,6,9,12,15,17,20,23,25,27)]
names(earnings) <- c("Year","Total_Earnings", "Under_9th_grade", "Some_High_School", "High_School_Completion", "Some_College", "Associates", "Total_Bach_Higher", "Bachelors", "Masters", "Professional", "Doctors")
```

```{r}
male_earnings <- earnings[c(7:24),]
male_earnings$Gender <- rep("Male", len = nrow(male_earnings))
female_earnings <- earnings[c(31:48),]
female_earnings$Gender <- rep("Female", len = nrow(female_earnings))
median_earnings <- rbind(male_earnings, female_earnings)

male_earnings_constant <- earnings[c(56:73),]
male_earnings_constant$Gender <- rep("Male", len = nrow(male_earnings_constant))
female_earnings_constant <- earnings[c(80:97),]
female_earnings_constant$Gender <- rep("Female", len = nrow(female_earnings_constant))
median_earnings_constant <- rbind(male_earnings_constant, female_earnings_constant)


male_full_count <- earnings[c(105:122),]
male_full_count$Gender <- rep("Male", len = nrow(male_full_count))
female_full_count <- earnings[c(129:146),]
female_full_count$Gender <- rep("Female", len = nrow(female_full_count))
fulltime_count <- rbind(male_full_count, female_full_count)
colnames(fulltime_count)[2:12] <- paste(colnames(fulltime_count)[2:12],"Count",sep="_")

male_full_perc <- earnings[c(154:171),]
male_full_perc$Gender <- rep("Male", len = nrow(male_full_perc))
female_full_perc <- earnings[c(178:195),]
female_full_perc$Gender <- rep("Female", len = nrow(female_full_perc))
fulltime_perc <- rbind(male_full_perc, female_full_perc)

```


```{r}
temp <- full_join(alledu, enrollment, by = "Year")
temp2 <- full_join(temp, expenditures, by = "Year")
temp3 <- full_join(temp2, gdp_income, by = "Year")
temp4 <- full_join(temp3, median_earnings, by = c("Year", "Gender"))
temp5 <- full_join(temp3, median_earnings_constant, by = c("Year", "Gender"))
```

```{r}
Earnings <- full_join(temp4, fulltime_count, by = c("Year", "Gender"))
Earnings_constant <- full_join(temp5, fulltime_count, by = c("Year", "Gender"))
```

